[package]
name = "ext2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = "0.6.1"
bitflags = "1.3.2"
uuid = "1.3.0"
null-terminated = "0.3.17"
rustyline = "11.0.0"